name: Build and deploy Next.js app to Azure Web App - qa-sen-member

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Node 18+ is also fine

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Install sharp specifically for Linux
      - name: Install sharp for Linux
        run: npm install --platform=linux --arch=x64 sharp

      # 5. Build Next.js app
      - name: Build the Next.js app
        run: npm run build

      # 6. Optional: run tests if you have any
      - name: Run tests (optional)
        run: npm run test --if-present

      # 7. Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Download build artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # 2. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'qa-sen-member'   # Replace with your Azure Web App name
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_89D0A419D473475FA38A34AC7E4D964F }}
